# MSU Deterministic Model

In [1]:
import numpy as np
import pandas as pd

from classes.geography_processing import Geoprocessing
from classes.model import Model
from classes.scenario import Scenario

In [4]:
# Set up scenario
scenario = Scenario({
    'name': 1,
    'limit_to_england' : True
})

# Process and save geographic data (only needed when hospital data changes)
geo = Geoprocessing(); geo.run()

# Set up model
model = Model(
    scenario=scenario,
    geodata=pd.read_csv('processed_data/processed_data.csv'))

# Run model
model.run()

In [5]:
model.full_results.head().T

LSOA,ADUR001A,ADUR001B,ADUR001C,ADUR001D,ADUR001E
nearest_ivt_unit,BN25BE,BN25BE,BN112DH,BN25BE,BN112DH
nearest_ivt_time,11,12,11,12,10
nearest_mt_unit,BN25BE,BN25BE,BN25BE,BN25BE,BN25BE
nearest_mt_time,11,12,13,12,13
transfer_unit,BN25BE,BN25BE,BN25BE,BN25BE,BN25BE
transfer_required,False,False,True,False,True
transfer_time,0,0,24,0,24
area_lower,Adur 001A,Adur 001B,Adur 001C,Adur 001D,Adur 001E
Admissions,1.333333,1.666667,2.0,2.0,3.666667
England,1,1,1,1,1
Admissions_2025_Est,1.5481,1.9352,2.3222,2.3222,4.2573
drip_ship_ivt_time,121,122,121,122,120
drip_ship_mt_time,241,242,265,242,264
nlvo_no_treatment_mrs_0-2,0.58,0.58,0.58,0.58,0.58
nlvo_no_treatment_utility,0.59964,0.59964,0.59964,0.59964,0.59964
lvo_no_treatment_mrs_0-2,0.265,0.265,0.265,0.265,0.265
lvo_no_treatment_utility,0.33261,0.33261,0.33261,0.33261,0.33261
nlvo_drip_ship_ivt_mrs_0-2,0.700497,0.700046,0.700497,0.700046,0.700947
nlvo_drip_ship_ivt_mrs_shift,-0.611717,-0.609338,-0.611717,-0.609338,-0.614095
nlvo_drip_ship_ivt_utility,0.711035,0.710625,0.711035,0.710625,0.711445
nlvo_drip_ship_ivt_utility_shift,0.111395,0.110985,0.111395,0.110985,0.111805
lvo_drip_ship_ivt_mrs_0-2,0.324881,0.32459,0.324881,0.32459,0.325172
lvo_drip_ship_ivt_mrs_shift,-0.273106,-0.271595,-0.273106,-0.271595,-0.274618
lvo_drip_ship_ivt_utility,0.387616,0.38734,0.387616,0.38734,0.387892
lvo_drip_ship_ivt_utility_shift,0.055006,0.05473,0.055006,0.05473,0.055282
lvo_drip_ship_mt_mrs_0-2,0.39117,0.390542,0.376218,0.390542,0.376836
lvo_drip_ship_mt_mrs_shift,-0.594643,-0.591528,-0.520433,-0.591528,-0.523502
lvo_drip_ship_mt_utility,0.452569,0.45198,0.438498,0.45198,0.439082
lvo_drip_ship_mt_utility_shift,0.119959,0.11937,0.105888,0.11937,0.106472
lvo_drip_ship_ivt_mt_mrs_0-2,0.39117,0.390542,0.376218,0.390542,0.376836
lvo_drip_ship_ivt_mt_mrs_shift,-0.594643,-0.591528,-0.520433,-0.591528,-0.523502
lvo_drip_ship_ivt_mt_utility,0.452569,0.45198,0.438498,0.45198,0.439082
lvo_drip_ship_ivt_mt_utility_shift,0.119959,0.11937,0.105888,0.11937,0.106472
mothership_ivt_time,121,122,123,122,123
mothership_mt_time,181,182,183,182,183
nlvo_mothership_ivt_mrs_0-2,0.700497,0.700046,0.699596,0.700046,0.699596
nlvo_mothership_ivt_mrs_shift,-0.611717,-0.609338,-0.606957,-0.609338,-0.606957
nlvo_mothership_ivt_utility,0.711035,0.710625,0.710215,0.710625,0.710215
nlvo_mothership_ivt_utility_shift,0.111395,0.110985,0.110575,0.110985,0.110575
lvo_mothership_ivt_mrs_0-2,0.324881,0.32459,0.3243,0.32459,0.3243
lvo_mothership_ivt_mrs_shift,-0.273106,-0.271595,-0.270086,-0.271595,-0.270086
lvo_mothership_ivt_utility,0.387616,0.38734,0.387064,0.38734,0.387064
lvo_mothership_ivt_utility_shift,0.055006,0.05473,0.054454,0.05473,0.054454
lvo_mothership_mt_mrs_0-2,0.429398,0.428752,0.428107,0.428752,0.428107
lvo_mothership_mt_mrs_shift,-0.785154,-0.781922,-0.778692,-0.781922,-0.778692
lvo_mothership_mt_utility,0.488194,0.487596,0.486998,0.487596,0.486998
lvo_mothership_mt_utility_shift,0.155584,0.154986,0.154388,0.154986,0.154388
lvo_mothership_ivt_mt_mrs_0-2,0.429398,0.428752,0.428107,0.428752,0.428107
lvo_mothership_ivt_mt_mrs_shift,-0.785154,-0.781922,-0.778692,-0.781922,-0.778692
lvo_mothership_ivt_mt_utility,0.488194,0.487596,0.486998,0.487596,0.486998
lvo_mothership_ivt_mt_utility_shift,0.155584,0.154986,0.154388,0.154986,0.154388

In [6]:
model.full_results.describe().T

,count,mean,std,min,25%,50%,75%,max
nearest_ivt_time,32843.0,13.123466,7.928949e+00,0.000000,7.000000,12.000000,17.000000,68.000000
nearest_mt_time,32843.0,24.978808,1.603702e+01,0.000000,13.000000,22.000000,33.000000,121.000000
transfer_time,32843.0,19.603416,1.818187e+01,0.000000,0.000000,20.000000,31.000000,104.000000
Admissions,32843.0,2.466063,1.418715e+00,0.100000,1.333333,2.333333,3.333333,19.333333
England,32843.0,1.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000
Admissions_2025_Est,32843.0,2.863328,1.647257e+00,0.116100,1.548100,2.709200,3.870300,22.447800
drip_ship_ivt_time,32843.0,123.123466,7.928949e+00,110.000000,117.000000,122.000000,127.000000,178.000000
drip_ship_mt_time,32843.0,262.726882,2.105696e+01,230.000000,245.000000,260.000000,275.000000,362.000000
nlvo_no_treatment_mrs_0-2,32843.0,0.580000,0.000000e+00,0.580000,0.580000,0.580000,0.580000,0.580000
nlvo_no_treatment_utility,32843.0,0.599640,0.000000e+00,0.599640,0.599640,0.599640,0.599640,0.599640
lvo_no_treatment_mrs_0-2,32843.0,0.265000,5.551200e-17,0.265000,0.265000,0.265000,0.265000,0.265000
lvo_no_treatment_utility,32843.0,0.332610,5.551200e-17,0.332610,0.332610,0.332610,0.332610,0.332610
nlvo_drip_ship_ivt_mrs_0-2,32843.0,0.699528,3.591355e-03,0.674224,0.697789,0.700046,0.702294,0.705425
nlvo_drip_ship_ivt_mrs_shift,32843.0,-0.606621,1.893538e-02,-0.637800,-0.621221,-0.609338,-0.597421,-0.474014
nlvo_drip_ship_ivt_utility,32843.0,0.710152,3.272701e-03,0.687043,0.708568,0.710625,0.712672,0.715522
nlvo_drip_ship_ivt_utility_shift,32843.0,0.110512,3.272701e-03,0.087403,0.108928,0.110985,0.113032,0.115882
lvo_drip_ship_ivt_mrs_0-2,32843.0,0.324268,2.297649e-03,0.308532,0.323139,0.324590,0.326045,0.328088
lvo_drip_ship_ivt_mrs_shift,32843.0,-0.269933,1.192206e-02,-0.289793,-0.279159,-0.271595,-0.264058,-0.188668
lvo_drip_ship_ivt_utility,32843.0,0.387034,2.182114e-03,0.372088,0.385961,0.387340,0.388722,0.390661
lvo_drip_ship_ivt_utility_shift,32843.0,0.054424,2.182114e-03,0.039478,0.053351,0.054730,0.056112,0.058051
lvo_drip_ship_mt_mrs_0-2,32843.0,0.377715,1.295124e-02,0.318383,0.370055,0.379314,0.388662,0.398093
lvo_drip_ship_mt_mrs_shift,32843.0,-0.527859,6.430280e-02,-0.629042,-0.582195,-0.535798,-0.489854,-0.232346
lvo_drip_ship_mt_utility,32843.0,0.439874,1.225505e-02,0.383028,0.432672,0.441420,0.450215,0.459055
lvo_drip_ship_mt_utility_shift,32843.0,0.107264,1.225505e-02,0.050418,0.100062,0.108810,0.117605,0.126445
lvo_drip_ship_ivt_mt_mrs_0-2,32843.0,0.377715,1.295124e-02,0.318383,0.370055,0.379314,0.388662,0.398093
lvo_drip_ship_ivt_mt_mrs_shift,32843.0,-0.527861,6.429519e-02,-0.629042,-0.582195,-0.535798,-0.489854,-0.232346
lvo_drip_ship_ivt_mt_utility,32843.0,0.439874,1.225505e-02,0.383028,0.432672,0.441420,0.450215,0.459055
lvo_drip_ship_ivt_mt_utility_shift,32843.0,0.107264,1.225505e-02,0.050418,0.100062,0.108810,0.117605,0.126445
mothership_ivt_time,32843.0,134.978808,1.603702e+01,110.000000,123.000000,132.000000,143.000000,231.000000
mothership_mt_time,32843.0,194.978808,1.603702e+01,170.000000,183.000000,192.000000,203.000000,291.000000
nlvo_mothership_ivt_mrs_0-2,32843.0,0.694118,7.372320e-03,0.648767,0.690500,0.695521,0.699596,0.705425
nlvo_mothership_ivt_mrs_shift,32843.0,-0.578169,3.867497e-02,-0.637800,-0.606957,-0.585471,-0.559066,-0.342369
nlvo_mothership_ivt_utility,32843.0,0.705217,6.730731e-03,0.663638,0.701922,0.706502,0.710215,0.715522
nlvo_mothership_ivt_utility_shift,32843.0,0.105577,6.730731e-03,0.063998,0.102282,0.106862,0.110575,0.115882
lvo_mothership_ivt_mrs_0-2,32843.0,0.320848,4.607020e-03,0.293748,0.318517,0.321691,0.324300,0.328088
lvo_mothership_ivt_mrs_shift,32843.0,-0.252219,2.381274e-02,-0.289793,-0.270086,-0.256547,-0.240116,-0.113097
lvo_mothership_ivt_utility,32843.0,0.383785,4.375583e-03,0.358031,0.381572,0.384586,0.387064,0.390661
lvo_mothership_ivt_utility_shift,32843.0,0.051175,4.375583e-03,0.025421,0.048962,0.051976,0.054454,0.058051
lvo_mothership_mt_mrs_0-2,32843.0,0.420434,1.023887e-02,0.360282,0.415257,0.422311,0.428107,0.436513
lvo_mothership_mt_mrs_shift,32843.0,-0.740394,5.106879e-02,-0.820830,-0.778692,-0.749706,-0.714488,-0.441349
lvo_mothership_mt_utility,32843.0,0.479864,9.533311e-03,0.423396,0.475066,0.481622,0.486998,0.494782
lvo_mothership_mt_utility_shift,32843.0,0.147254,9.533311e-03,0.090786,0.142456,0.149012,0.154388,0.162172
lvo_mothership_ivt_mt_mrs_0-2,32843.0,0.420434,1.023887e-02,0.360282,0.415257,0.422311,0.428107,0.436513
lvo_mothership_ivt_mt_mrs_shift,32843.0,-0.740394,5.106879e-02,-0.820830,-0.778692,-0.749706,-0.714488,-0.441349
lvo_mothership_ivt_mt_utility,32843.0,0.479864,9.533311e-03,0.423396,0.475066,0.481622,0.486998,0.494782
lvo_mothership_ivt_mt_utility_shift,32843.0,0.147254,9.533311e-03,0.090786,0.142456,0.149012,0.154388,0.162172

In [7]:
model.full_results.to_csv('./output/single_run.csv')

In [8]:
x = model.full_results.copy()
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32843 entries, ADUR001A to YORK024F
Data columns (total 51 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   nearest_ivt_unit                     32843 non-null  object
 1   nearest_ivt_time                     32843 non-null  int64
 2   nearest_mt_unit                      32843 non-null  object
 3   nearest_mt_time                      32843 non-null  int64
 4   transfer_unit                        32843 non-null  object
 5   transfer_required                    32843 non-null  bool
 6   transfer_time                        32843 non-null  int64
 7   area_lower                           32843 non-null  object
 8   Admissions                           32843 non-null  float64
 9   England                              32843 non-null  int64
 10  Admissions_2025_Est                  32843 non-null  float64
 11  drip_ship_ivt_time                   32843 non-null  int64
 12  drip_ship_mt_time                    32843 non-null  int64
 13  nlvo_no_treatment_mrs_0-2            32843 non-null  float64
 14  nlvo_no_treatment_utility            32843 non-null  float64
 15  lvo_no_treatment_mrs_0-2             32843 non-null  float64
 16  lvo_no_treatment_utility             32843 non-null  float64
 17  nlvo_drip_ship_ivt_mrs_0-2           32843 non-null  float64
 18  nlvo_drip_ship_ivt_mrs_shift         32843 non-null  float64
 19  nlvo_drip_ship_ivt_utility           32843 non-null  float64
 20  nlvo_drip_ship_ivt_utility_shift     32843 non-null  float64
 21  lvo_drip_ship_ivt_mrs_0-2            32843 non-null  float64
 22  lvo_drip_ship_ivt_mrs_shift          32843 non-null  float64
 23  lvo_drip_ship_ivt_utility            32843 non-null  float64
 24  lvo_drip_ship_ivt_utility_shift      32843 non-null  float64
 25  lvo_drip_ship_mt_mrs_0-2             32843 non-null  float64
 26  lvo_drip_ship_mt_mrs_shift           32843 non-null  float64
 27  lvo_drip_ship_mt_utility             32843 non-null  float64
 28  lvo_drip_ship_mt_utility_shift       32843 non-null  float64
 29  lvo_drip_ship_ivt_mt_mrs_0-2         32843 non-null  float64
 30  lvo_drip_ship_ivt_mt_mrs_shift       32843 non-null  float64
 31  lvo_drip_ship_ivt_mt_utility         32843 non-null  float64
 32  lvo_drip_ship_ivt_mt_utility_shift   32843 non-null  float64
 33  mothership_ivt_time                  32843 non-null  int64
 34  mothership_mt_time                   32843 non-null  int64
 35  nlvo_mothership_ivt_mrs_0-2          32843 non-null  float64
 36  nlvo_mothership_ivt_mrs_shift        32843 non-null  float64
 37  nlvo_mothership_ivt_utility          32843 non-null  float64
 38  nlvo_mothership_ivt_utility_shift    32843 non-null  float64
 39  lvo_mothership_ivt_mrs_0-2           32843 non-null  float64
 40  lvo_mothership_ivt_mrs_shift         32843 non-null  float64
 41  lvo_mothership_ivt_utility           32843 non-null  float64
 42  lvo_mothership_ivt_utility_shift     32843 non-null  float64
 43  lvo_mothership_mt_mrs_0-2            32843 non-null  float64
 44  lvo_mothership_mt_mrs_shift          32843 non-null  float64
 45  lvo_mothership_mt_utility            32843 non-null  float64
 46  lvo_mothership_mt_utility_shift      32843 non-null  float64
 47  lvo_mothership_ivt_mt_mrs_0-2        32843 non-null  float64
 48  lvo_mothership_ivt_mt_mrs_shift      32843 non-null  float64
 49  lvo_mothership_ivt_mt_utility        32843 non-null  float64
 50  lvo_mothership_ivt_mt_utility_shift  32843 non-null  float64
dtypes: bool(1), float64(38), int64(8), object(4)
memory usage: 12.8+ MB